# Makefile for HashTable tests

# Uncomment the tests as you're ready for them

all:
	gcc -o hash_table_test main.c hashtable.c -Wall -Werror -I .


clean:
	rm hash_table_test
	
	# Add commands here to remove executables